### ISSUE TITLE
Retry job only when internet is connected

### ISSUE THREAD

**Issue by vishgoel007** [SimonErm/react-native-job-queue#31]
Can we retry job only when internet is connected ?
And can we retry job after some interval ?

**Comment by SimonErm** [comment]
At work i use react-native-netinfo to get the networkstate and just start the queue if internet is available. I don't know if that would fit your needs.

Retry after interval is currently not implemented. But feel free to do a PR.

**Comment by vishgoel007** [comment]
@SimonErm I made it work using react-native-netinfo and ```setInterval``` for retry job after some interval.

**Comment by SimonErm** [comment]
👍
