### ISSUE TITLE
Retry Failed Job?

### ISSUE THREAD

**Issue by myckhel** [SimonErm/react-native-job-queue#37]
## Question
Is it possible to retry failed job?

**Comment by SimonErm** [comment]
Yes you can pass attempts to the job options. https://simonerm.github.io/react-native-job-queue/docs/classes/queue#addjob
The attempts configure the number of retries.

**Comment by myckhel** [comment]
> Yes you can pass attempts to the job options. https://simonerm.github.io/react-native-job-queue/docs/classes/queue#addjob
> The attempts configure the number of retries.

I meant manually retrying a particular job without letting it retry automatically.

**Comment by SimonErm** [comment]
That's not possible this way, but you could set the attempts to 0 and use the workers  onFailure callback to add a new job with the same payload, which should lead to the same behaviour.

**Comment by myckhel** [comment]
Okay.
Nice
