### ISSUE TITLE
Retry/Remove failed jobs

### ISSUE THREAD

**Issue by SimonErm** [SimonErm/react-native-job-queue#44]
Currently there is no convenient method to retry or remove failed jobs.

**Comment by myckhel** [comment]
I am thinking of having `Job` class such as `Queue` class and `Worker` class.
Imagining the `Job` class should have:
Properties:
- active
- attempts
- created
- failed
- id
- metaData
- payload
- priority
- timeout
- workerName

Methods:
- remove
- retry
- cancel

Good idea?

**Comment by SimonErm** [comment]
I don't think this would give us any benefits or am i wrong?
Furthermore i think the job is a kind of dto sine it's serialized and passed to the bridge.
