### ISSUE TITLE
Active jobs not being reprocessed after app is terminated

### ISSUE THREAD

**Issue by projuljustin** [SimonErm/react-native-job-queue#45]
I am running 0.3.1 and if I have active tasks running when the app is force closed, they are not being retried when the app is reopened. If I run getJobs, the only jobs returned are the failed ones.

This was previously working when I was on 0.2.7.

**Comment by SimonErm** [comment]
Does this occure on iOS or Android?
I tried to reproduce this by running the example app on android with an emulator, but it's working as expected.

**Comment by projuljustin** [comment]
Oh I'm currently testing on an iOS device

**Comment by SimonErm** [comment]
On iOS Simulator it works for me too. Are you sure the jobs did not finish before the app was closed?
Can you provide a minimal example to reproduce? Because it seems like i can't reproduce this with the example app.

**Comment by projuljustin** [comment]
I'm using 0.4.0 now and am not having the issue

**Comment by orlandokaramani** [comment]
I also encountered this issue, i had to call queue.start() as soon as my app was relaunched from killed state.
