### ISSUE TITLE
Upgrade to react@17.0.2

### ISSUE THREAD

**Issue by Tim4497** [SimonErm/react-native-job-queue#69]
I get the following error on `npm i react-native-job-queue`:

`npm ERR! Found: react@17.0.2`
`npm ERR! node_modules/react`
`npm ERR!   react@"^17.0.2" from the root project`
`npm ERR! `
`npm ERR! Could not resolve dependency:`
`npm ERR! peer react@"^16.5.0" from react-native-job-queue@0.4.1`
`npm ERR! node_modules/react-native-job-queue`
`npm ERR!   react-native-job-queue@"*" from the root project`

**Comment by SimonErm** [comment]
Hey,  i have to lower the peer dependecy restrictions. As workaround you can add `--legacy-peer-deps` to install command.

**Comment by ninacoder-info** [comment]
Hi could you please update it, i got same problem, I can't use work around because the project will send to many people and i want them just to run "npm install " when working on the project 

Please :)

**Comment by SimonErm** [comment]
Resolved in 0.4.2
