### ISSUE TITLE
How can i re try a job that has been failed ? ( basically persisting the job and re trying it when app is back online or re opened)

### ISSUE THREAD

**Issue by Udit-takkar** [SimonErm/react-native-job-queue#71]
i have to upload an image to server but if the device looses connection then it should persist the task and then retry it again when app comes back online or app is re started by the user. How can i do this?

**Comment by SimonErm** [comment]
You can implement this by using react-native-netinfo to get the connection state. Just configure an onFailure callback which adds the failed job again with startQueue flag set to false and attemts set to 0. Than you just have to call queue.start() if the connection state listener of react-native-netinfo is called.
https://github.com/SimonErm/react-native-job-queue/issues/37
https://github.com/SimonErm/react-native-job-queue/issues/31

**Comment by Udit-takkar** [comment]
@SimonErm  thanks

**Comment by Udit-takkar** [comment]
> You can implement this by using react-native-netinfo to get the connection state. Just configure an onFailure callback which adds the failed job again with startQueue flag set to false and attemts set to 0. Than you just have to call queue.start() if the connection state listener of react-native-netinfo is called. #37 #31

@SimonErm   tried this . not working
it goes into infinte loop if request fails even though i am passing flag as false.

**Comment by SimonErm** [comment]
Can you provide a code example to reproduce?

**Comment by SimonErm** [comment]
Stale
