### ISSUE TITLE
Async function call doesn't run in Worker

### ISSUE THREAD

**Issue by therealtgd** [SimonErm/react-native-job-queue#84]
When there is no internet connection in my app I want to enable the user to make changes, optimistically save them in a MobX store, and add a request to save the changes on the server to the queue. Then when the user is back online I want to trigger the queue to run the requests, which I was able to do by using [react-native-community/netinfo](https://github.com/react-native-netinfo/react-native-netinfo), by listening to network connection change and using `queue.start()` when the connection is re-established. But the request doesn't run, and nothing gets logged to the console from the `onStart` function.

I provided the queue code below. What am I doing wrong?

```
import queue, { Worker } from 'react-native-job-queue';

queue.configure({
  onQueueFinish: (executedJobs) =>
    console.log('Queue stopped and executed', executedJobs),
});

queue.addWorker(
  new Worker('request-worker'),
  async (request) => await request(),
  {
    onStart: async (id) => {
      console.log(`Job ${id} has started processing.`);
    },
  },

);

export default queue;
```

Below is an example of how I add a job.

```
const request = async () => await APIManager.get('some_url')
queue.addJob('request-worker', request, {}, false);

```

**Comment by SimonErm** [comment]
Hello @therealtgd,
The problem is that you try to pass a function as job payload, but that is not possible (https://github.com/SimonErm/react-native-job-queue/issues/22).
Instead you should pass the request payload as job payload and implement the request as the worker.

**Comment by therealtgd** [comment]
I refactored it to work as you said, but now the request doesn't finish. It only finishes when I rerun the app.

**Comment by therealtgd** [comment]
Nevermind I think it works now.

**Comment by therealtgd** [comment]
Here is the code for delete in  APIManager:

```
const APIManager = {
  delete: async (url) => {
    let res;
    try {
      res = await axios.delete(url);
    } catch (err) {
      res = err.response;
    }
    return handleResponse(res);
  },
};
```
