### ISSUE TITLE
Error upon fresh installation

### ISSUE THREAD

**Issue by Stophface** [SimonErm/react-native-job-queue#91]
I freshly installed the library and try to run `const queue = await queueFactory();` which gives me 

> TypeError: (0, _reactNativeJobQueue.default) is not a function. (In '(0, _reactNativeJobQueue.default)()', '(0, _reactNativeJobQueue.default)' is an instance of Queue)

any ideas what might cause the error?

**Comment by SimonErm** [comment]
Seems like you trying to call the queue as function.
It should look like this: https://simonerm.github.io/react-native-job-queue/docs/classes/queue#usage

**Comment by SimonErm** [comment]
I close this because of inactivity
